name: 'Code Lints'
on: ['push', 'pull_request']
jobs:
    phpcs:
        name: 'Parallel Lint'
        runs-on: 'ubuntu-20.04'
        strategy:
            matrix:
                php-version:
                    - '8.0'
        steps:
            - name: 'Checkout'
              uses: 'actions/checkout@v2'
            - name: 'Setup PHP'
              uses: 'shivammathur/setup-php@v2'
              with:
                  php-version: '${{ matrix.php-version }}'
                  coverage: 'none'
                  tools: 'cs2pr'
            - name: 'Install dependencies'
              uses: 'ramsey/composer-install@v1'
            - name: 'Run Parallel Lint'
              run: 'vendor/bin/parallel-lint src/ tests/ --checkstyle | cs2pr'
