name: 'Tests'
on: ['push', 'pull_request']
jobs:
    phpunit:
        name: 'PHPUnit'
        runs-on: 'ubuntu-20.04'
        strategy:
            matrix:
                php-version:
                    - '8.0'
        steps:
            - name: 'Checkout'
              uses: 'actions/checkout@v2'
            - name: 'Setup PHP'
              uses: 'shivammathur/setup-php@v2'
              with:
                  php-version: '${{ matrix.php-version }}'
                  coverage: 'none'
                  ini-values: 'zend.assertions=1'
            - name: 'Install dependencies'
              uses: 'ramsey/composer-install@v1'
            - name: 'Run PHPUnit'
              run: 'vendor/bin/phpunit --coverage-clover=coverage.xml'
